language: go

go:
  - 1.12.x

go_import_path: github.com/carlos-shift/opencensus-go-exporter-stackdriver

env:
  global:
    GO111MODULE=on

install:
  - go mod download
  - make install-tools

script:
  - make travis-ci

after_success:
  - bash <(curl -s https://codecov.io/bash)